### ISSUE TITLE
Bug: doryd crashes if StorageClass does'nt have any parameters: section

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/dory#32]
I have a StorageClass with parameters: section missing

Like
 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: database
provisioner: dev.hpe.com/nimble
``` 

I do see this error on the container running the doryd engine, which this exception logged, and the container restart happens.
 
```
[root@csimbe13-b05 quick-start]# docker ps -a | grep nimble
76d85e347364        nimblestorage/doryd@sha256:ed0fc2cbd942f35d0efe549fd39365226250a0e5ab7e51927ba6d84f239cf0b1                                      "doryd /etc/kubernete"   About a minute ago   Exited (2) About a minute ago                       k8s_dory_doryd-t2n0k_default_5b45a0da-1258-11e8-acd9-ecb1d7a4aa90_151
[root@csimbe13-b05 quick-start]# docker logs 76d85e347364
09:48:30 provisioner.go:184: provisioner (prefix=dev.hpe.com) is being created with instance id 57acbbec-222f-4391-a0dd-745502bc5941.
09:48:30 claim.go:85: processAddedClaim: provisioner:dev.hpe.com/hpe pvc:example-claim1  class:transactionaldb
09:48:30 provisioner.go:106: addMessageChan: creating 484f3213-1559-11e8-acd9-ecb1d7a4aa90
09:48:30 claim.go:85: processAddedClaim: provisioner:dev.hpe.com/hpe pvc:example-claim  class:from-production
09:48:30 provisioner.go:106: addMessageChan: creating b05c02bb-1557-11e8-acd9-ecb1d7a4aa90
panic: assignment to entry in nil map
 
goroutine 129 [running]:
nimblestorage/pkg/k8s/provisioner.(*Provisioner).newPersistentVolume(0xc420508300, 0xc420902200, 0x34, 0xc4202800f0, 0xc4208cf800, 0xc420654600, 0x0, 0xc420913b30, 0x43105e)
        /opt/build/workspace/hostint_go_default/src/nimblestorage/pkg/k8s/provisioner/volume.go:161 +0x215
nimblestorage/pkg/k8s/provisioner.(*Provisioner).provisionVolume(0xc420508300, 0xc4208cf800, 0xc420654600)
        /opt/build/workspace/hostint_go_default/src/nimblestorage/pkg/k8s/provisioner/provisioner.go:305 +0x353
nimblestorage/pkg/k8s/provisioner.(*Provisioner).processAddedClaim(0xc420508300, 0xc4208cf800)
        /opt/build/workspace/hostint_go_default/src/nimblestorage/pkg/k8s/provisioner/claim.go:87 +0x578
created by nimblestorage/pkg/k8s/provisioner.(*Provisioner).addedClaim
        /opt/build/workspace/hostint_go_default/src/nimblestorage/pkg/k8s/provisioner/claim.go:63 +0x14d
[root@csimbe13-b05 quick-start]#
```

**Comment by e4jet** [comment]
pull request #41 should address this

**Comment by e4jet** [comment]
this is available in nimblestorage/kube-storage-controller:edge as of now
